name: Publish

on:
  push:
    branches: [ master ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json before"
        run: cat ./package.json
      - name: "Setup node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix:  ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json after"
        run: cat ./package.json

  build:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
